name: "AI Dependency & Migration Validator"
description: "Validate dependency versioning and database migrations using AI"
inputs:
  GITHUB_TOKEN:
    description: "GitHub token to interact with the repository"
    required: true
  OPENAI_API_KEY:
    description: "OpenAI API key for GPT"
    required: false
  ANTHROPIC_API_KEY:
    description: "Anthropic API key for Claude"
    required: false
  GOOGLE_API_KEY:
    description: "Google API key for Gemini models"
    required: false
  GOOGLE_VERTEX_PROJECT:
    description: "Google Cloud project ID for Vertex AI"
    required: false
  GOOGLE_VERTEX_LOCATION:
    description: "Google Cloud location for Vertex AI"
    required: false
    default: "us-central1"
  AI_PROVIDER:
    description: "AI provider to use (openai, anthropic, google, or vertex)"
    required: false
    default: "anthropic"
  exclude:
    description: "Glob patterns to exclude files from analysis"
    required: false
    default: ""
  COOKBOOK_URL:
    description: "URL to fetch validation rules cookbook from"
    required: true
  GOOGLE_VERTEX_SA_KEY_B64:
    description: "Base64 encoded Google service account key for Vertex AI authentication"
    required: false

runs:
  using: "node20"
  main: "dist/src/main.js"

branding:
  icon: "shield"
  color: "blue"